function [fitresult, gof] = createFit(fpr, trp)
%CREATEFIT(FPR,TRP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fpr
%      Y Output: trp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Feb-2014 18:40:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fpr, trp );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.993278469569718 0.0101510000463831 -1.10616395884806 -23.7320485422603];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'trp vs. fpr', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'fpr' );
ylabel( 'trp' );
grid on


